### ISSUE TITLE
Add Response Code to the collected data

### ISSUE THREAD

**Issue by tyge68** [hoodoo-digital/locust-influxdb-listener#2]
It would be nice to be able to easily organize the error / exception also by response code.

Currently it store the "full" error as a string, which make it more complex to group by response code.

**Comment by pjcalvo** [comment]
I will work on that.

**Comment by pjcalvo** [comment]
I am sorry I just notice that you did open a PR for it.

**Comment by pjcalvo** [comment]
Fixed on [PR-3](https://github.com/hoodoo-digital/locust-influxdb-listener/pull/3)
