### ISSUE TITLE
Thank you. I am making a locust-timestream-listener.

### ISSUE THREAD

**Issue by komikoni** [hoodoo-digital/locust-influxdb-listener#4]
locust-influxdb-listener is a great tool.

I wanted to use Amazon Timestream instead of influxdb.
([influxdb Cloud ](https://aws.amazon.com/marketplace/pp/InfluxData-Inc-InfluxDB-Cloud/B08234JZPS)did not work because it is V2)

Copy this repository
I made a **locust-timestream-listener**.
https://github.com/komikoni/locust-timestream-listener

Not yet completed (locust-grafana-dashboard.json, etc.)

First of all, I wanted to express my gratitude.

**Comment by pjcalvo** [comment]
You are welcome.
